In [1]:
# import dependencies
import pandas as pd
import datetime as dt

In [2]:
# attempt to increase col display
pd.set_option('display.max_columns', 28)

In [3]:
# read in csv
policy_df = pd.read_csv('Raw/policy_list.csv')
policy_df.sample(7)

,ID,COUNTRY_NAME,ISO3,ISO2,POLICY_TYPE,POLICY_SUBTYPE,START_DATE,END_DATE,AIR,AIR_TYPE,TARGETS_AIR,LAND,LAND_TYPE,TARGETS_LAND,...,VISA_BAN,VISA_BAN_TYPE,VISA_BAN_LIST,CITIZEN_EXCEP,CITIZEN_EXCEP_LIST,COUNTRY_EXCEP,COUNTRY_EXCEP_LIST,WORK_EXCEP,SOURCE0,SOURCE1,SOURCE2,SOURCE3,SOURCE4,SOURCE5
244,NL75,American Samoa,ASM,AS,COMPLETE,CITIZEN_EXCEP,12_01_20,01_03_21,0,NaN,NaN,0,NaN,NaN,...,0,NaN,NaN,1,citizens,0,NaN,0,https://web.archive.org/web/20201204024521/htt...,NaN,NaN,NaN,NaN,NaN
218,MS5,Belize,BLZ,BZ,COMPLETE,CITIZEN_EXCEP,03_23_20,04_05_20,0,NaN,NaN,0,NaN,NaN,...,0,NaN,NaN,1,"Belizeans, diplomats residing in Belize, and f...",0,NaN,0,http://web.archive.org/web/20200503130408/http...,NaN,NaN,NaN,NaN,NaN
1180,NL17,Malawi,MWI,MW,PARTIAL,BORDER_CLOSURE,09_01_20,NONE,0,NaN,NaN,1,All,NaN,...,0,NaN,NaN,0,NaN,0,NaN,0,https://web.archive.org/web/20201128035131/htt...,https://web.archive.org/web/20200924024353/htt...,NaN,NaN,NaN,NaN
406,EB 6,Viet Nam,VNM,VN,COMPLETE,WORK_EXCEP,05_07_20,NONE,0,NaN,NaN,0,NaN,NaN,...,0,NaN,NaN,1,citizens,0,NaN,1,https://web.archive.org/web/20200621113610/htt...,https://web.archive.org/save/http://news.chinh...,NaN,NaN,NaN,NaN
1135,LM4,Georgia,GEO,GE,PARTIAL,BORDER_CLOSURE,01_29_20,NONE,1,Specific,China,0,NaN,NaN,...,0,NaN,NaN,0,NaN,0,NaN,0,https://web.archive.org/web/20201021051351/htt...,https://web.archive.org/web/20201210184616/htt...,NaN,NaN,NaN,NaN
746,127,Papua New Guinea,PNG,PG,PARTIAL,BORDER_CLOSURE,02_09_20,02_16_20,0,NaN,NaN,1,Specific,Indonesia,...,0,NaN,NaN,0,NaN,0,NaN,0,https://web.archive.org/web/20200320135415/htt...,NaN,NaN,NaN,NaN,NaN
618,SN24,Sweden,SWE,SE,PARTIAL,CITIZENSHIP_BAN,08_05_20,08_15_20,0,NaN,NaN,0,NaN,NaN,...,0,NaN,NaN,0,NaN,0,NaN,0,https://web.archive.org/web/20200804113540/htt...,NaN,NaN,NaN,NaN,NaN

In [4]:
# viewing current columns
policy_df.columns

Index(['ID', 'COUNTRY_NAME', 'ISO3', 'ISO2', 'POLICY_TYPE', 'POLICY_SUBTYPE',
       'START_DATE', 'END_DATE', 'AIR', 'AIR_TYPE', 'TARGETS_AIR', 'LAND',
       'LAND_TYPE', 'TARGETS_LAND', 'SEA', 'SEA_TYPE', 'TARGETS_SEA',
       'CITIZEN', 'CITIZEN_LIST', 'HISTORY_BAN', 'HISTORY_BAN_LIST', 'REFUGEE',
       'REFUGEE_LIST', 'VISA_BAN', 'VISA_BAN_TYPE', 'VISA_BAN_LIST',
       'CITIZEN_EXCEP', 'CITIZEN_EXCEP_LIST', 'COUNTRY_EXCEP',
       'COUNTRY_EXCEP_LIST', 'WORK_EXCEP', 'SOURCE0', 'SOURCE1', 'SOURCE2',
       'SOURCE3', 'SOURCE4', 'SOURCE5'],
      dtype='object')

In [5]:
# taking columns subset
policy_df = policy_df[['ID', 'COUNTRY_NAME', 'ISO3', 'POLICY_TYPE', 'POLICY_SUBTYPE',
       'START_DATE', 'AIR', 'AIR_TYPE', 'TARGETS_AIR', 'LAND',
       'LAND_TYPE', 'TARGETS_LAND', 'SEA', 'SEA_TYPE', 'TARGETS_SEA',
       'CITIZEN', 'CITIZEN_LIST', 'HISTORY_BAN', 'HISTORY_BAN_LIST', 'REFUGEE',
       'REFUGEE_LIST', 'VISA_BAN', 'VISA_BAN_TYPE', 'VISA_BAN_LIST',
       'CITIZEN_EXCEP', 'CITIZEN_EXCEP_LIST', 'COUNTRY_EXCEP',
       'COUNTRY_EXCEP_LIST', 'WORK_EXCEP']]
policy_df.columns

Index(['ID', 'COUNTRY_NAME', 'ISO3', 'POLICY_TYPE', 'POLICY_SUBTYPE',
       'START_DATE', 'AIR', 'AIR_TYPE', 'TARGETS_AIR', 'LAND', 'LAND_TYPE',
       'TARGETS_LAND', 'SEA', 'SEA_TYPE', 'TARGETS_SEA', 'CITIZEN',
       'CITIZEN_LIST', 'HISTORY_BAN', 'HISTORY_BAN_LIST', 'REFUGEE',
       'REFUGEE_LIST', 'VISA_BAN', 'VISA_BAN_TYPE', 'VISA_BAN_LIST',
       'CITIZEN_EXCEP', 'CITIZEN_EXCEP_LIST', 'COUNTRY_EXCEP',
       'COUNTRY_EXCEP_LIST', 'WORK_EXCEP'],
      dtype='object')

In [6]:
# renaming the columns
policy_df.columns = ['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Air_ban',
                             'Air_ban_type', 'Air_ban_info', 'Land_ban', 'Land_ban_type', 'Land_ban_info', 
                             'Sea_ban', 'Sea_ban_type', 'Sea_ban_info','Citizen_ban', 'Citizen_ban_info', 
                             'Travel_history_ban', 'Travel_history_ban_info', 
                             'Refugee_ban', 'Refugee_ban_info', 
                             'Visa_ban', 'Visa_ban_list', 'Visa_ban_info', 
                             'Citizen_exceptions', 'Citizen_exceptions_info', 
                             'Country_exceptions', 'Country_exceptions_info', 'Work_exceptions']
policy_df.columns

Index(['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype',
       'Policy_start_date', 'Air_ban', 'Air_ban_type', 'Air_ban_info',
       'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type',
       'Sea_ban_info', 'Citizen_ban', 'Citizen_ban_info', 'Travel_history_ban',
       'Travel_history_ban_info', 'Refugee_ban', 'Refugee_ban_info',
       'Visa_ban', 'Visa_ban_list', 'Visa_ban_info', 'Citizen_exceptions',
       'Citizen_exceptions_info', 'Country_exceptions',
       'Country_exceptions_info', 'Work_exceptions'],
      dtype='object')

In [7]:
# re-viewing the columns
policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
0,118,Brunei Darussalam,BRN,COMPLETE,ESSENTIAL_ONLY,03_23_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0
1,259,Morocco,MAR,COMPLETE,ESSENTIAL_ONLY,03_20_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0
2,362,"Korea, Democratic People's Republic of",PRK,COMPLETE,ESSENTIAL_ONLY,01_22_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0
3,386,Marshall Islands,MHL,COMPLETE,ESSENTIAL_ONLY,03_08_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0
4,470,Lao People's Democratic Republic,LAO,COMPLETE,ESSENTIAL_ONLY,03_16_20,0,NaN,NaN,0,NaN,NaN,0,NaN,...,0,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaN,0

In [8]:
# checking which cols have null values
policy_df.isnull().sum()

Policy_id                     0
Country                       0
Country_id                    0
Policy_type                   0
Policy_subtype                0
Policy_start_date             0
Air_ban                       0
Air_ban_type                891
Air_ban_info               1034
Land_ban                      0
Land_ban_type              1084
Land_ban_info              1156
Sea_ban                       0
Sea_ban_type               1211
Sea_ban_info               1242
Citizen_ban                   0
Citizen_ban_info           1209
Travel_history_ban            0
Travel_history_ban_info    1154
Refugee_ban                   0
Refugee_ban_info           1270
Visa_ban                      0
Visa_ban_list              1181
Visa_ban_info              1236
Citizen_exceptions            0
Citizen_exceptions_info     904
Country_exceptions            0
Country_exceptions_info    1101
Work_exceptions               0
dtype: int64

In [9]:
# renaming NaNs
policy_df.fillna('no policy', inplace=True)
policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
0,118,Brunei Darussalam,BRN,COMPLETE,ESSENTIAL_ONLY,03_23_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
1,259,Morocco,MAR,COMPLETE,ESSENTIAL_ONLY,03_20_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
2,362,"Korea, Democratic People's Republic of",PRK,COMPLETE,ESSENTIAL_ONLY,01_22_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
3,386,Marshall Islands,MHL,COMPLETE,ESSENTIAL_ONLY,03_08_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
4,470,Lao People's Democratic Republic,LAO,COMPLETE,ESSENTIAL_ONLY,03_16_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [10]:
# finding length of dataframe
len(policy_df)

1271

In [11]:
# finding number of countries in df
len(policy_df['Country_id'].unique())

243

In [ ]:
# sorting the country id alphabetically
sorted_policy_df = policy_df.sort_values('Country_id')
sorted_policy_df.head()

In [13]:
# finding dtype for Start Date col
sorted_policy_df['Policy_start_date'].dtype

dtype('O')

In [14]:
# impossible date
sorted_policy_df[sorted_policy_df['Policy_start_date'] == '04_31_20']

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
93,NL3,Ecuador,ECU,COMPLETE,ESSENTIAL_ONLY,04_31_20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [15]:
# formatting dates for use in datetime
# replacing nons and 0s with fake date 
dates_list = [x.replace('_', '-') for x in sorted_policy_df['Policy_start_date']]
dates_list_start = ['01-01-01' if x == 'NONE' or x == '0' else x for x in dates_list]
# educated guess as to end date of errant date shown in above cell
dates_list_edited = ['04-21-20' if x == '04-31-20' else x for x in dates_list_start]

In [16]:
# replacing Start Date col w/ edited dates list
sorted_policy_df['Policy_start_date'] = dates_list_edited
sorted_policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
194,CH7,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,03-16-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, permanent residents",0,no policy,0
296,CH8,Aruba,ABW,COMPLETE,SPECIFIC_COUNTRY,07-10-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
84,MS50,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,03-26-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
295,CH6,Aruba,ABW,COMPLETE,SPECIFIC_COUNTRY,07-01-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
81,MG12,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,03-26-20,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [17]:
# converting Start Date col to dtype datetime
sorted_policy_df['Policy_start_date'] = pd.to_datetime(sorted_policy_df['Policy_start_date'])

In [18]:
# checking dtype
sorted_policy_df['Policy_start_date'].dtype

dtype('<M8[ns]')

In [19]:
# sorting by country id then start date
double_sorted_policy_df = sorted_policy_df.sort_values(['Country_id','Policy_start_date'])
double_sorted_policy_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
194,CH7,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,2020-03-16,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, permanent residents",0,no policy,0
217,MS49,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,2020-03-16,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, permanent residents, family members ...",0,no policy,0
209,MG0,Aruba,ABW,COMPLETE,CITIZEN_EXCEP,2020-03-17,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,residents,0,no policy,0
84,MS50,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,2020-03-26,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
81,MG12,Aruba,ABW,COMPLETE,ESSENTIAL_ONLY,2020-03-26,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0

In [20]:
# keeping only the rows with the most recent date for each country
last_date_df = double_sorted_policy_df.drop_duplicates(subset='Country_id', keep='last')
last_date_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,...,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
296,CH8,Aruba,ABW,COMPLETE,SPECIFIC_COUNTRY,2020-07-10,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
1017,11020,Afghanistan,AFG,PARTIAL,BORDER_CLOSURE,2020-03-24,1,Specific,all commercial flights suspended except for so...,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
1252,SN63,Angola,AGO,PARTIAL,BORDER_CLOSURE,2020-10-19,1,Specific,"Afghanistan, Aland Islands, Albania, Algeria, ...",1,All,no policy,1,All,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,0,no policy,0,no policy,0
299,CK4,Anguilla,AIA,COMPLETE,SPECIFIC_COUNTRY,2020-07-12,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"citizens, residents",1,"Aruba, Bonaire, St Eustatius and Saba, Belize,...",0
423,EB65,Ã…land Islands,ALA,COMPLETE,WORK_EXCEP,2020-11-19,0,no policy,no policy,0,no policy,no policy,0,no policy,...,0,no policy,0,no policy,0,no policy,0,no policy,no policy,1,"nationals of Finland, family members of nation...",1,"Vactican City, Australia, South Korea, Japan, ...",1

In [21]:
# len of df
len(last_date_df)

243

In [22]:
# removing country ids that are different in other dfs
country_ids = ['VIR', 'XKX', 'SOL']
ind_to_drop = []
for c in country_ids:
    ind_to_drop.append(last_date_df[last_date_df['Country_id'] == c].index[0])
ind_to_drop

[416, 225, 95]

In [23]:
last_date_df = last_date_df.drop(ind_to_drop)

In [24]:
# showing cols of df
last_date_df.columns

Index(['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype',
       'Policy_start_date', 'Air_ban', 'Air_ban_type', 'Air_ban_info',
       'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type',
       'Sea_ban_info', 'Citizen_ban', 'Citizen_ban_info', 'Travel_history_ban',
       'Travel_history_ban_info', 'Refugee_ban', 'Refugee_ban_info',
       'Visa_ban', 'Visa_ban_list', 'Visa_ban_info', 'Citizen_exceptions',
       'Citizen_exceptions_info', 'Country_exceptions',
       'Country_exceptions_info', 'Work_exceptions'],
      dtype='object')

In [26]:
# separating out only rows where a complete ban was in effect, saving only cols that apply
full_closures_df = last_date_df[last_date_df['Policy_type'] == 'COMPLETE'][
    ['Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 
    'Policy_start_date', 'Citizen_exceptions', 'Citizen_exceptions_info', 
    'Country_exceptions','Country_exceptions_info', 'Work_exceptions']]
full_closures_df.reset_index(inplace=True, drop=True)

# exporting full closure table to csv
full_closures_df.to_csv('Clean/full_closures_table.csv', index=False)
full_closures_df.head()

,Policy_id,Country_id,Policy_type,Policy_subtype,Policy_start_date,Citizen_exceptions,Citizen_exceptions_info,Country_exceptions,Country_exceptions_info,Work_exceptions
0,CH8,ABW,COMPLETE,SPECIFIC_COUNTRY,2020-07-10,1,"residents with prior authorization, non-reside...",1,"Antiga and Barbuda, The Bahamas, Barbados, Cub...",0
1,CK4,AIA,COMPLETE,SPECIFIC_COUNTRY,2020-07-12,1,"citizens, residents",1,"Aruba, Bonaire, St Eustatius and Saba, Belize,...",0
2,EB65,ALA,COMPLETE,WORK_EXCEP,2020-11-19,1,"nationals of Finland, family members of nation...",1,"Vactican City, Australia, South Korea, Japan, ...",1
3,NL75,ASM,COMPLETE,CITIZEN_EXCEP,2020-12-01,1,citizens,0,no policy,0
4,EB18,ATG,COMPLETE,SPECIFIC_COUNTRY,2020-04-23,0,no policy,1,Dominican Republic,0

In [27]:
# separating out only rows where a partial ban was in effect, saving only cols that apply
partial_closures_df = last_date_df[last_date_df['Policy_type'] == 'PARTIAL'][['Policy_id', 'Country', 
       'Country_id', 'Policy_type', 'Policy_subtype',
       'Policy_start_date', 'Air_ban', 'Air_ban_type', 'Air_ban_info',
       'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type',
       'Sea_ban_info', 'Citizen_ban', 'Citizen_ban_info', 'Travel_history_ban',
       'Travel_history_ban_info', 'Refugee_ban', 'Refugee_ban_info',
       'Visa_ban', 'Visa_ban_list', 'Visa_ban_info']]
partial_closures_df.reset_index(inplace=True, drop=True)
partial_closures_df.head()

,Policy_id,Country,Country_id,Policy_type,Policy_subtype,Policy_start_date,Air_ban,Air_ban_type,Air_ban_info,Land_ban,Land_ban_type,Land_ban_info,Sea_ban,Sea_ban_type,Sea_ban_info,Citizen_ban,Citizen_ban_info,Travel_history_ban,Travel_history_ban_info,Refugee_ban,Refugee_ban_info,Visa_ban,Visa_ban_list,Visa_ban_info
0,11020,Afghanistan,AFG,PARTIAL,BORDER_CLOSURE,2020-03-24,1,Specific,all commercial flights suspended except for so...,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy
1,SN63,Angola,AGO,PARTIAL,BORDER_CLOSURE,2020-10-19,1,Specific,"Afghanistan, Aland Islands, Albania, Algeria, ...",1,All,no policy,1,All,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy
2,1940,Albania,ALB,PARTIAL,BORDER_CLOSURE,2020-03-24,0,no policy,no policy,0,no policy,no policy,1,Specific,All ferries to/from Italy & other red areas ar...,0,no policy,0,no policy,0,no policy,0,no policy,no policy
3,5314,United Arab Emirates,ARE,PARTIAL,VISA_BAN,2020-04-03,0,no policy,no policy,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,1,specific,New visa seekers and existing valid visa holders
4,140705,Argentina,ARG,PARTIAL,BORDER_CLOSURE,2020-11-01,1,Specific,Only citizens allowed to fly,0,no policy,no policy,0,no policy,no policy,0,no policy,0,no policy,0,no policy,0,no policy,no policy

In [28]:
# partial closure -- border closure
# by this point refugee bans are no longer in the dataframe (bans have ended by that time point) 
partial_borders_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'BORDER_CLOSURE'][[
        'Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Air_ban', 'Air_ban_type',
        'Air_ban_info', 'Land_ban', 'Land_ban_type', 'Land_ban_info', 'Sea_ban', 'Sea_ban_type', 'Sea_ban_info']]
)

# partial closure -- visa ban
partial_visa_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'VISA_BAN'][[
        'Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Visa_ban_list', 
        'Visa_ban_info']]
).reset_index(drop=True)


# partial closure -- citizenship ban
partial_citizenship_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'CITIZENSHIP_BAN'][[
        'Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Citizen_ban_info']]
).reset_index(drop=True)


# partial closure -- history ban
partial_history_df = pd.DataFrame(
    partial_closures_df[partial_closures_df['Policy_subtype'] == 'HISTORY_BAN'][[
        'Policy_id', 'Country_id', 'Policy_type', 'Policy_subtype', 'Policy_start_date', 'Travel_history_ban_info']]
).reset_index(drop=True)

# exporting partial closure tables to csv
partial_borders_df.to_csv('Clean/partial_borders_table.csv', index=False)
partial_visa_df.to_csv('Clean/partial_visa_table.csv', index=False)
partial_citizenship_df.to_csv('Clean/partial_citizenship_table.csv', index=False)
partial_history_df.to_csv('Clean/partial_history_table.csv', index=False)

In [29]:
# separating out only rows where no ban was in effect, saving only cols that apply
no_closures_df = last_date_df[last_date_df['Policy_type'] == 'NOPOLICYIMPLEMENTED'][
    ['Policy_id', 'Country', 'Country_id', 'Policy_type', 'Policy_subtype']]
no_closures_df.reset_index(inplace=True, drop=True)

no_closures_df.to_csv('Clean/no_closures_table.csv', index=False)
no_closures_df.head()

  Policy_id     Country Country_id          Policy_type Policy_subtype
0      EB45     Andorra        AND  NOPOLICYIMPLEMENTED           NONE
1      EB10  Antarctica        ATA  NOPOLICYIMPLEMENTED           NONE
2      MS82    Guernsey        GGY  NOPOLICYIMPLEMENTED           NONE
3      MS40        Guam        GUM  NOPOLICYIMPLEMENTED           NONE
4      MS81      Jersey        JEY  NOPOLICYIMPLEMENTED           NONE

In [36]:
# reading in csvs
vaccinations_df = pd.read_csv('Clean/vaccinations_cleaned.csv')
travel_df = pd.read_csv('Clean/travel_restrictions_clean.csv')

In [37]:
# number of countries in each df - travel restrictions has the most
len(vaccinations_df['Country'].unique()), len(travel_df['Country'].unique()), len(last_date_df['Country'].unique())

(57, 250, 240)

In [38]:
# creating a countries names and ids table
# subsetting each CSV source df for only country names and IDs
vacc_countries_df = vaccinations_df[['Country', 'Country_id']]
immig_countries_df = last_date_df[['Country', 'Country_id']]
travel_countries_df = travel_df[['Country', 'Country_id']]

# outer merging the travel restrictions and immigration restriction dfs 
# to capture country names not in the other table
first_countries_merge = travel_countries_df.merge(
    immig_countries_df, how='outer', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP'
)
print(len(first_countries_merge))

# outer merging the vaccinations and first merge dfs
# to capture country names not in the other table
full_merge = first_countries_merge.merge(
    vacc_countries_df, how='outer', on='Country_id', suffixes=('', '_DROP')).drop(columns='Country_DROP'
)
print(len(full_merge))
full_merge.head()

250
250

                            Country Country_id
0                          Kiribati        KIR
1                            Kosovo        RKS
2                            Kuwait        KWT
3                        Kyrgyzstan        KGZ
4  Lao People's Democratic Republic        LAO

In [39]:
# checking to see if there are any duplicates in the merged tables -- there aren't
full_merge[full_merge.duplicated() == True]

Empty DataFrame
Columns: [Country, Country_id]
Index: []

In [40]:
# making the table alphabetical, resetting the index, saving to a new descriptive name
countries_names_ids_df = full_merge.sort_values('Country').reset_index(drop=True)

#checking for duplicate values
countries_names_ids_df[countries_names_ids_df.duplicated(subset='Country_id', keep=False) == True]

Empty DataFrame
Columns: [Country, Country_id]
Index: []

In [41]:
# checking for null values
countries_names_ids_df[countries_names_ids_df['Country'].isnull() == True]

Empty DataFrame
Columns: [Country, Country_id]
Index: []

In [42]:
# exporting country table to csv
countries_names_ids_df.to_csv('Clean/country.csv', index=False)